apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywebapp.client.fullname" . }}
  labels:
    app: {{ include "mywebapp.client.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "mywebapp.client.fullname" . }}
