apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywebapp.fullname" . }}-svc
  labels:
    app: {{ include "mywebapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mywebapp.fullname" . }}
  ports:
    - protocol: TCP
      name: http-metrics
      port: {{ .Values.service.port }}
      targetPort: 8080
